### ISSUE TITLE
LoadP3D issues - Pure3D branch -  Unreconized Chunk

### ISSUE THREAD

**Issue by bobthecooldad** [plowteam/donut#12]
Hi,
Trying to understand the code and what it currently does, currently it gets to loading the krustyPoster.bmp from the l1z1.p3d, Upon the next loop of block i get a begin chunk type of 48347 that becomes an unreconized chunk of (1900/36).
(I am using Ghidra to see where the data is and trying to compare to how the loader is choosing what memory ranges to load in)
Where do you get the information for the chunk types and how they are linked back to the game itself, which parts of the rewrite work and which bits need work?

Is there a discord chat (current link in readme is dead)?

**Comment by AlexHaber** [comment]
Have you tried checking [this list](https://github.com/plowteam/donut/blob/master/dev/Chunks.md) for info about implemented chunks?

**Comment by handsomematt** [comment]
pure3d branch is a complete refactor of the pure3d loading, as such only the texture loader is there.
master branch has lots of stuff, but seems to be broken as of right now.

I fixed the Discord link if you do want to join
