### ISSUE TITLE
cmake issue

### ISSUE THREAD

**Issue by coreybruce** [plowteam/donut#13]
```
[corey@corey-pc Storage]$ git clone --recursive https://github.com/plowteam/donut.git
Cloning into 'donut'...
remote: Enumerating objects: 3931, done.
remote: Counting objects: 100% (586/586), done.
remote: Compressing objects: 100% (464/464), done.
remote: Total 3931 (delta 327), reused 346 (delta 121), pack-reused 3345
Receiving objects: 100% (3931/3931), 6.41 MiB | 5.25 MiB/s, done.
Resolving deltas: 100% (2769/2769), done.
[corey@corey-pc Storage]$ cd donut
[corey@corey-pc donut]$ cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-linux
CMake Error at /usr/share/cmake-3.20/Modules/CMakeDetermineSystem.cmake:129 (message):
  Could not find toolchain file: /scripts/buildsystems/vcpkg.cmake
Call Stack (most recent call first):
  CMakeLists.txt:16 (project)


CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
```

**Comment by coreybruce** [comment]
Doing ```cmake .``` on it's own got me this far 

```
[corey@corey-pc donut]$ cmake .
-- The C compiler identification is GNU 10.2.0
-- The CXX compiler identification is GNU 10.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at /usr/share/cmake-3.20/Modules/CheckIncludeFileCXX.cmake:56 (configure_file):
  configure_file attempted to configure a file:
  /mnt/Storage/donut/CMakeFiles/CMakeTmp/CheckIncludeFile.cxx into a source
  directory.
Call Stack (most recent call first):
  CMakeLists.txt:36 (check_include_file_cxx)


-- Configuring incomplete, errors occurred!
See also "/mnt/Storage/donut/CMakeFiles/CMakeOutput.log".
```

**Comment by handsomematt** [comment]
> Could not find toolchain file: /scripts/buildsystems/vcpkg.cmake

your $VCPKG_ROOT is not set

**Comment by coreybruce** [comment]
Why do we need to use vcpkg on LInux? couldn't this just use normal cmake, rely on already package manager and installed packages because I already have SDL2 ect installed on my Linux OS

**Comment by coreybruce** [comment]
```
[corey@corey-pc donut]$ cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=/usr/share/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-linux
-- Configuring done
CMake Warning (dev) in CMakeLists.txt:
  Policy CMP0111 is not set: An imported target missing its location property
  fails during generation.  Run "cmake --help-policy CMP0111" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  IMPORTED_LOCATION not set for imported target "fmt::fmt" configuration
  "RelWithDebInfo".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /mnt/Storage/donut/build
[corey@corey-pc donut]$ cmake --build build -j6
src/CMakeFiles/donut.dir/build.make:1072: *** target pattern contains no '%'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:124: src/CMakeFiles/donut.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
[corey@corey-pc donut]$ cmake ./build
-- Configuring done
CMake Warning (dev) in CMakeLists.txt:
  Policy CMP0111 is not set: An imported target missing its location property
  fails during generation.  Run "cmake --help-policy CMP0111" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  IMPORTED_LOCATION not set for imported target "fmt::fmt" configuration
  "RelWithDebInfo".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /mnt/Storage/donut/build
```

Build instructions with cmake didn't work so I made some changes but even tho it gave a warning and said it finished I am not sure where the binary is.

**Comment by RossComputerGuy** [comment]
Using vpkg is unconventional as the majority of people DO NOT have it installed on their Linux systems. This is exactly why the majority of distros have a package manager and why most packages are available on a package manager that is not vpkg. Plus most people have `sudo` access so this means being able to use their distro's package manager is just fine.

**Comment by coreybruce** [comment]
> There's no requirement on vcpkg, but you were literally passing it as the toolchain file and it didn't exist.
> 
> The code isn't good and will require some of your own patching to compile on Linux probably.

True but we were following the instructions.

Is there any possibility of patching the code to fix the issue?

**Comment by handsomematt** [comment]
Sure if someone who actually uses Linux (like yourself) wants to patch it to work on Linux it wouldn't be too hard.

**Comment by coreybruce** [comment]
Ah ok so you don't have much experience in Linux I understand, I might see if I can get @RossComputerGuy or another friend to lend a hand to send in a patch to fix it :)

**Comment by aylaylay** [comment]
> 
> 
> Ah ok so you don't have much experience in Linux I understand, I might see if I can get @RossComputerGuy or another friend to lend a hand to send in a patch to fix it :)

linux is shit mate calm down yeah?

**Comment by coreybruce** [comment]
> > Ah ok so you don't have much experience in Linux I understand, I might see if I can get @RossComputerGuy or another friend to lend a hand to send in a patch to fix it :)
> 
> linux is shit mate calm down yeah?

Lol didn't expect to find childish low IQ comments like this on Github but I guess here I am seeing one.

Idk man your the one that seems to be pretty angry here not me and oh you say Linux is so "shit" yet most of the worlds hardware is powered by it between the super computers down to the Android phones most of the population has and the very router you used to connect to the internet you used to make this silly comment..

Do yourself a favour and do some research or at least think before you make angry comments, you don't want to make a fool of yourself and waste peoples times like ourselves trying to resolve and fix issues..

@handsomematt Looks like we have a troll on the issue report.

**Comment by aylaylay** [comment]
no one cares about linux mate

**Comment by coreybruce** [comment]
Says who? can I proof that no one cares or are you just assuming that when literally the industry standards of the world use Linux basically debunking your assumption?

So tell me why exactly does it suck and why are you being so negative and non inclusive to Linux and their users ?

**Comment by aylaylay** [comment]
ok cool

**Comment by coreybruce** [comment]
So instead of answering the question your just going to continue to waste all of our time? lol ok

**Comment by aylaylay** [comment]
ok

**Comment by coreybruce** [comment]
So anyways @handsomematt we will look into the code and see what fixes can be done on the C code tho anyone else more qualified than me on C can freely join in to contribute and help.

**Comment by aylaylay** [comment]
It's C++ mate, not C

**Comment by coreybruce** [comment]
Yeah ok good on you, anyways people will help, that's what the community and open source are great at!

**Comment by coreybruce** [comment]
Latest patches has fixed it and @RossComputerGuy  has it working on Void Linux using a Nvidia GPU but I am having issues with openal and on my pi 4 it doesn't give any errors but doesn't launch.  Is there a minimal requirement for the OpenGL version?

Pi 4 log
```
[corey@corey-pi4 SimpsonsHit&Run]$ ./donut
bash: ./donut: cannot execute binary file: Exec format error
[corey@corey-pi4 SimpsonsHit&Run]$ ./donut
+---------------------------------------------------+
|    _____        /--------------------------\      |
|   /     \      |                            |     |
| \/\/     |    /     donut game               \    |
|  |  (o)(o)    |                              |    |
|  C   .---_)   \_   _________________________/     |
|   | |.___|      | /                               |
|   |  \__/      <_/                                |
|   /_____\                                         |
|  /_____/ \                                        |
| /         \                                       |
+---------------------------------------------------+

hellooooooooooo new york!!!!
Initializing SDL...
SDL Version/Compiled 2.0.14
SDL Version/Linked 2.0.14
OpenGL version loaded: 2.1
Vendor: Broadcom
Renderer: V3D 4.2
Version: 2.1 Mesa 21.0.3
```

**Comment by rndtrash** [comment]
> Latest patches has fixed it and @RossComputerGuy has it working on Void Linux using a Nvidia GPU but I am having issues with openal and on my pi 4 it doesn't give any errors but doesn't launch. Is there a minimal requirement for the OpenGL version and is it OpenGl 3.3?
> 
> PC log
> 
> ```
> [corey@corey-pc SimpsonsHit&Run]$ ./donut
> +---------------------------------------------------+
> |    _____        /--------------------------\      |
> |   /     \      |                            |     |
> | \/\/     |    /     donut game               \    |
> |  |  (o)(o)    |                              |    |
> |  C   .---_)   \_   _________________________/     |
> |   | |.___|      | /                               |
> |   |  \__/      <_/                                |
> |   /_____\                                         |
> |  /_____/ \                                        |
> | /         \                                       |
> +---------------------------------------------------+
> 
> hellooooooooooo new york!!!!
> Initializing SDL...
> SDL Version/Compiled 2.0.14
> SDL Version/Linked 2.0.14
> OpenGL version loaded: 4.6
> Vendor: NVIDIA Corporation
> Renderer: GeForce GTX 1060 6GB/PCIe/SSE2
> Version: 4.6.0 NVIDIA 460.73.01
> 
> [ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
> [ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
> X Error of failed request:  GLXBadContext
>   Major opcode of failed request:  151 (GLX)
>   Minor opcode of failed request:  4 (X_GLXDestroyContext)
>   Serial number of failed request:  387
>   Current serial number in output stream:  387
> ```
> 
> Pi 4 log
> 
> ```
> [corey@corey-pi4 SimpsonsHit&Run]$ ./donut
> +---------------------------------------------------+
> |    _____        /--------------------------\      |
> |   /     \      |                            |     |
> | \/\/     |    /     donut game               \    |
> |  |  (o)(o)    |                              |    |
> |  C   .---_)   \_   _________________________/     |
> |   | |.___|      | /                               |
> |   |  \__/      <_/                                |
> |   /_____\                                         |
> |  /_____/ \                                        |
> | /         \                                       |
> +---------------------------------------------------+
> 
> hellooooooooooo new york!!!!
> Initializing SDL...
> SDL Version/Compiled 2.0.14
> SDL Version/Linked 2.0.14
> OpenGL version loaded: 2.1
> Vendor: Broadcom
> Renderer: V3D 4.2
> Version: 2.1 Mesa 21.0.3
> ```

Weird thing: for some reason it crashes with GLXBadContext if donut hasn't found any resources. Copying all the files from TS:H&R to build/bin folder solved that issue for me.
And yes, it requires at least OpenGL 4 support

**Comment by rndtrash** [comment]
Hmm, here's my log when donut has no resources:
```
+---------------------------------------------------+
|    _____        /--------------------------\      |
|   /     \      |                            |     |
| \/\/     |    /     donut game               \    |
|  |  (o)(o)    |                              |    |
|  C   .---_)   \_   _________________________/     |
|   | |.___|      | /                               |
|   |  \__/      <_/                                |
|   /_____\                                         |
|  /_____/ \                                        |
| /         \                                       |
+---------------------------------------------------+

hellooooooooooo new york!!!!
Initializing SDL...
SDL Version/Compiled 2.0.12
SDL Version/Linked 2.0.12
OpenGL version loaded: 4.6
Vendor: NVIDIA Corporation
Renderer: GeForce GTX 1050 Ti/PCIe/SSE2
Version: 4.6.0 NVIDIA 460.73.01

BDB1539 Build signature doesn't match environment
X Error of failed request:  GLXBadContext
  Major opcode of failed request:  151 (GLX)
  Minor opcode of failed request:  4 (X_GLXDestroyContext)
  Serial number of failed request:  391
  Current serial number in output stream:  391
```
Lets move our discussion to donut Discord server☺

**Comment by coreybruce** [comment]
> Hmm, here's my log when donut has no resources:
> 
> ```
> +---------------------------------------------------+
> |    _____        /--------------------------\      |
> |   /     \      |                            |     |
> | \/\/     |    /     donut game               \    |
> |  |  (o)(o)    |                              |    |
> |  C   .---_)   \_   _________________________/     |
> |   | |.___|      | /                               |
> |   |  \__/      <_/                                |
> |   /_____\                                         |
> |  /_____/ \                                        |
> | /         \                                       |
> +---------------------------------------------------+
> 
> hellooooooooooo new york!!!!
> Initializing SDL...
> SDL Version/Compiled 2.0.12
> SDL Version/Linked 2.0.12
> OpenGL version loaded: 4.6
> Vendor: NVIDIA Corporation
> Renderer: GeForce GTX 1050 Ti/PCIe/SSE2
> Version: 4.6.0 NVIDIA 460.73.01
> 
> BDB1539 Build signature doesn't match environment
> X Error of failed request:  GLXBadContext
>   Major opcode of failed request:  151 (GLX)
>   Minor opcode of failed request:  4 (X_GLXDestroyContext)
>   Serial number of failed request:  391
>   Current serial number in output stream:  391
> ```
> 
> Lets move our discussion to donut Discord server

Sure, just mention @gameslayer, I am on your Discord server already :)

**Comment by RossComputerGuy** [comment]
Why is he blocked?

**Comment by hipocentrum** [comment]
Who's Steve Jobs?

**Comment by fuzunspm** [comment]
what an asshole (plowteam) + idiot
